 
// -------------------------------- SPRITE OFFSETS --------------------------------

.label SPRITE_OFFSET_UP = 10
.label SPRITE_OFFSET_DOWN = 21
.label SPRITE_OFFSET_LEFT = 0
.label SPRITE_OFFSET_RIGHT = 24

.label SPRITE_OFFSET_UP_LEFT = 4
.label SPRITE_OFFSET_UP_CENTER = 12
.label SPRITE_OFFSET_UP_RIGHT = 20

.label SPRITE_OFFSET_DOWN_LEFT = 4
.label SPRITE_OFFSET_DOWN_CENTER = 12
.label SPRITE_OFFSET_DOWN_RIGHT = 20

.label SPRITE_OFFSET_LEFT_UP = 11
.label SPRITE_OFFSET_LEFT_CENTER = 15
.label SPRITE_OFFSET_LEFT_DOWN = 20

.label SPRITE_OFFSET_RIGHT_UP = 11
.label SPRITE_OFFSET_RIGHT_CENTER = 15
.label SPRITE_OFFSET_RIGHT_DOWN = 20
