temp: .byte 0
temp1: .byte 0
temp2: .byte 0
temp3: .byte 0
temp4: .byte 0
tempA: .byte 0
tempB: .byte 0
tempC: .byte 0
tempD: .byte 0
tempX: .byte 0
tempY: .byte 0
tempXpos: .byte 0
tempYpos: .byte 0
